### ISSUE TITLE
Error running tube with urllib.request

### ISSUE THREAD

**Issue by jenmud** [divs4debu/Hobby#3]
I am getting the following issue with python 2.7 and python 3.5. I wonder if using the youtube API directly will be better. Then you can use `requests`

```
Hobby$ .tox/py27-lint/bin/tube 
Traceback (most recent call last):
  File ".tox/py27-lint/bin/tube", line 11, in <module>
    sys.exit(run())
  File "/Volumes/Data/Programming/Repos/Hobby/.tox/py27-lint/lib/python2.7/site-packages/tube/tube.py", line 104, in run
    qual = list(fetch_video_qualtiy(links))
  File "/Volumes/Data/Programming/Repos/Hobby/.tox/py27-lint/lib/python2.7/site-packages/tube/tube.py", line 68, in fetch_video_qualtiy
    youtube = YouTube(url)
  File "/Volumes/Data/Programming/Repos/Hobby/.tox/py27-lint/lib/python2.7/site-packages/pytube/api.py", line 66, in __init__
    self.from_url(url)
  File "/Volumes/Data/Programming/Repos/Hobby/.tox/py27-lint/lib/python2.7/site-packages/pytube/api.py", line 158, in from_url
    video_data = self.get_video_data()
  File "/Volumes/Data/Programming/Repos/Hobby/.tox/py27-lint/lib/python2.7/site-packages/pytube/api.py", line 254, in get_video_data
    response = urlopen(self.url)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 422, in open
    req.timeout = timeout
AttributeError: 'set' object has no attribute 'timeout'
```

**Comment by divs4debu** [comment]
Actually my exams are going thats why I am not able to give my time to it. I will look into what you r saying but I just need a little time. Till then if you want you can continue.. And you have done a great help thanks

**Comment by jenmud** [comment]
Sure, I am not sure if I like this `pytube`. I think that reading into the `youtube API` and using that directly would be better.

But I will stop till you have time to work on it. I have other things like [ruruki](https://www.github.com/optiver/ruruki) to work on.

**Comment by divs4debu** [comment]
Thanks for your sincere effort and i will read about YouTube api as you suggested and try to start work on it as soon as possible. All the best for ruruki
